<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Patient;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends BaseRepository
{
    public function save(Patient $entity)
    {
        $em = $this->getEntityManager();

        $em->persist($entity);
        $em->flush();
    }
}
