<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends BaseRepository
{
    public function createReservationDayQuery(\DateTime $dateTime, string $surgery): Query
    {
        $formattedDate = $dateTime->format('"Y-m-d H:i:s"');
        $replacedDate = str_replace("\"", "", $formattedDate);

        return $this->createQueryBuilder('reservation_table')
            ->where("reservation_table.reservation_day = '{$replacedDate}'")
            ->andWhere("reservation_table.surgery = '{$surgery}'")
            ->getQuery();
    }
}
