<?php

namespace AppBundle\Repository;

/**
 * ReservationDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findReservedDays(\DateTime $dateTime, string $surgery)
    {
        $dateFormatter = $dateTime->format('"Y-m-d H:i:s"');
        $replacedDate = str_replace("\"", "", $dateFormatter);

        return $this->createQueryBuilder('reservation_table')
            ->where("reservation_table.reservation_day = '{$replacedDate}'")
            ->andWhere("reservation_table.surgery = '{$surgery}'")
            ->getQuery();
    }
}
