<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends BaseRepository
{
    public function createReservationDayQuery(\DateTime $dateTime, string $surgery): Query
    {
        $formattedDate = $dateTime->format('"Y-m-d H:i:s"');
        $replacedDate = str_replace("\"", "", $formattedDate);

        return $this->createQueryBuilder('reservation_table')
            ->where("reservation_table.reservation_day = '{$replacedDate}'")
            ->andWhere("reservation_table.surgery = '{$surgery}'")
            ->getQuery();
    }

    public function createDateIntervalQuery( \DateTime $fromTime, \DateTime $toTime): Query
    {
        $formattedFromDate = $fromTime->format('"Y-m-d H:i:s"');
        $formattedToDate = $toTime->format('"Y-m-d H:i:s"');
        $replacedFromDate = str_replace("\"", "", $formattedFromDate);
        $replacedToDate = str_replace("\"", "", $formattedToDate);


        return $this->createQueryBuilder('reservation_table')
            ->where("reservation_table.reservation_day >= '{$replacedFromDate}'")
            ->andWhere("reservation_table.reservation_day <= '{$replacedToDate}'")
            ->getQuery();
    }

    public function removeReservationByHour(int $id, int $hour){

        $criteria =  ['id' => $id, 'hour' => $hour];

        $reservation = $this->findOneBy($criteria);

        $this->getEntityManager()->remove($reservation);
        $this->getEntityManager()->flush();

    }
}
