home:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }

ajax_router:
    path: /ajax-router/{template}
    defaults: { _controller: "AppBundle:Default:ajaxRouter", template: null }


code_result:
    path: /code-result
    defaults: { _controller: "AppBundle:Default:codeSearchResult" }

login:
    path: /login
    defaults: { _controller: "AppBundle:Default:login" }

logout:
    path: /logout
    defaults: { _controller: "AppBundle:Default:logout"}

registration:
    path: /registration
    defaults: { _controller: "AppBundle:Default:registration" }