parameters:
    app.reservation.repository.class: 'ApppBundle\Repository\ReservationRepository'
    app.patient.repository.class: 'ApppBundle\Repository\PatientRepository'

    app.patient.manager.class: 'AppBundle\Manager\PatientManager'
    app.reservation.manager.class: 'AppBundle\Manager\ReservationManager'

    app.patient.factory.class: 'AppBundle\Factory\PatientFactory'
    app.reservation.factory.class: 'AppBundle\Factory\ReservationFactory'

    app.breadcrumb.builder.class: 'AppBundle\Breadcrumb\BreadcrumbBuilder'


services:

    app.basemanager.abstract:
        abstract: true
        arguments:
          - "@doctrine.orm.entity_manager"
          - ~

    app.patient.manager:
        parent: "app.basemanager.abstract"
        class: "%app.patient.manager.class%"
        arguments:
          index_1: 'AppBundle\Entity\Patient'

    app.reservation.manager:
        parent: "app.basemanager.abstract"
        class: "%app.reservation.manager.class%"
        arguments:
          index_1: 'AppBundle\Entity\Reservation'



    app.patient.factory:
        class: '%app.patient.factory.class%'

    app.reservation.factory:
        class: '%app.reservation.factory.class%'

    app.breadcrumb.builder:
        class: '%app.breadcrumb.builder.class%'
        arguments:
            - '@router'