AppBundle\Entity\Patient:
    type: entity
    table: patient
    repositoryClass: AppBundle\Repository\PatientRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
            nullable: true
        lastname:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            unique: true
            nullable: true
        password:
            type: string
            length: 255
            nullable: false
    oneToMany:
      reservations:
        targetEntity: Reservation
        mappedBy: patient
    lifecycleCallbacks: {  }
