AppBundle\Entity\Reservation:
    type: entity
    table: reservation
    uniqueConstraints:
      reservation_day_and_hour:
          columns: [ reservation_day, hour ]

    repositoryClass: AppBundle\Repository\ReservationRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        reservation_day:
            type: datetime
        hour:
            type: integer
        description:
            type: string
            nullable: true
    manyToOne:
      patient:
        targetEntity: Patient
        inversedBy: reservations
    lifecycleCallbacks: {  }
