AppBundle\Entity\Reservation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ReservationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        reservation_day:
            type: datetime
            unique: true
    manyToOne:
      patient:
        targetEntity: Patient
        inversedBy: reservations
    lifecycleCallbacks: {  }
