AppBundle\Entity\Reservation:
    type: entity
    table: reservation
    repositoryClass: AppBundle\Repository\ReservationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        reservation_day:
            type: datetime
        hour:
            type: integer
        surgery:
            type: string
        code:
            type: string
    manyToOne:
      patient:
        targetEntity: Patient
        inversedBy: reservations
    lifecycleCallbacks: {  }
